swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /user/profile/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Retrieve all transactions for the current month 
      description: >
        This endpoint retrieves all transactions for the current month, grouped by account.
      parameters:
        - in: header
          name: Authorization
          required: true
          type: string
          description: Token JWT
        - in: body
          name: body
          description: Payload to filter transactions (optional)
          required: false
          schema:
            type: object
            properties:
              accountId:
                type: string
                description: Optional account ID to filter transactions
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

  /user/profile/transactions/{transactionId}/details:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Retrieve details of a specific transaction
      description: >
        This endpoint retrieves the details of a specific transaction by its ID.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction to retrieve
        - in: header
          name: Authorization
          required: true
          type: string
          description: Token JWT
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

  /user/profile/transactions/{transactionId}/category:
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update transaction category
      description: >
        This endpoint allows updating the category of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction to update
        - in: header
          name: Authorization
          required: true
          type: string
          description: Token JWT
        - in: body
          name: body
          description: The new transaction category
          required: true
          schema:
            $ref: '#/definitions/CategoryDetails'

      responses:
        '200':
          description: Transaction category updated successfully
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

    delete:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Delete transaction category
      description: >
        This endpoint allows deleting the category of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction for which the category will be deleted
        - in: header
          name: Authorization
          required: true
          type: string
          description: Token JWT
      responses:
        '200':
          description: Transaction category deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
                description: Confirmation message that the category was deleted
                example: "Transaction category deleted successfully."
        '400':
          description: Invalid request
        '404':
          description: Transaction or category not found
        '500':
          description: Internal server error

  /user/profile/transactions/{transactionId}/notes:
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update transaction notes
      description: >
        This endpoint allows updating the notes of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction to update
        - in: header
          name: Authorization
          required: true
          type: string
          description: Token JWT
        - in: body
          name: body
          description: The new transaction notes
          required: true
          schema:
            $ref: '#/definitions/NoteDetails'

      responses:
        '200':
          description: Transaction notes updated successfully
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal server error

    delete:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Delete transaction notes
      description: >
        This endpoint allows deleting the notes of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction for which the notes will be deleted
        - in: header
          name: Authorization
          required: true
          type: string
          description: Token JWT
      responses:
        '200':
          description: Transaction notes deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
                description: Confirmation message that the notes were deleted
                example: "Transaction notes deleted successfully."
        '400':
          description: Invalid request
        '404':
          description: Transaction or notes not found
        '500':
          description: Internal server error

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: The ID of the transaction
      
  TransactionDetails:
    type: object
    properties:
      id:
        type: string
        description: The ID of the transaction
      date:
        type: string
        format: date
        description: The date of the transaction
      description:
        type: string
        description: The description of the transaction
      amount:
        type: number
        format: float
        description: The amount of the transaction
      balance:
        type: number
        format: float
        description: The balance after the transaction
      type:
        type: string
        description: The type of the transaction
      category:
        type: string
        description: The category of the transaction
      notes:
        type: string
        description: Any notes associated with the transaction

  CategoryDetails:
    type: object
    properties:
      id: 
        type: string
        description: The ID of the transaction
      category: 
        type: string
        description: Any category associated with the transaction

  NoteDetails:
    type: object
    properties:
      id: 
        type: string
        description: The ID of the transaction
      note: 
        type: string
        description: Any note associated with the transaction
